version: '3'
services:
  update-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../server/config.json:/app/server/config.json
      - ../server/projects:/app/server/projects
    command: node server/index.js
    restart: unless-stopped
  
  update-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../server/config.json:/app/server/config.json
      - ../server/projects:/app/server/projects
      - ../server.log:/app/server.log
    command: node server/server-ui.js
    restart: unless-stopped 