version: '3.8'

# 这是一个docker-compose.override.yml示例文件
# 复制并重命名为docker-compose.override.yml以自定义本地开发环境

services:
  update-api:
    # 开发环境配置
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    # 挂载源代码以便实时更改
    volumes:
      - ../server:/app/server
    # 使用nodemon实现热重载
    command: npx nodemon server/index.js
    # 暴露调试端口
    ports:
      - "9229:9229"  # Node.js调试端口
  
  update-ui:
    # 开发环境配置
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    # 挂载源代码以便实时更改
    volumes:
      - ../server:/app/server
    # 使用nodemon实现热重载
    command: npx nodemon server/server-ui.js
    # 暴露调试端口
    ports:
      - "9230:9230"  # Node.js调试端口
  
  # 开发环境可能不需要Nginx
  # 如果需要，可以取消注释以下内容
  # nginx:
  #   ports:
  #     - "8000:80"  # 使用不同端口避免与本地服务冲突
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf 